blur-background-exclude = [
  # prevents picom from blurring the background
  "role   = 'xborder'",
  "role   = 'maim'",
  "name   = 'slop'"
];

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-method = "dual_kawase";
#blur-method = "kernel";

blur-kern = "3x3box";
#blur-method = "kernel";
blur-strength = 4;



#menu-opacity = 1;
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
#alpha-step = 0.06;

opacity-rule = [
      "80:class_g = 'Kitty'",
      "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

backend = "glx";

